### ISSUE TITLE
"Should handle setup for multiple clients" test is not testing anything

### ISSUE THREAD

**Issue by Naktibalda** [alexzywiak/socketTester#4]
https://github.com/alexzywiak/socketTester/blob/master/test/test.js#L25

``` js
    var client1 = {
      on: {
        'message': function(msg){
          expect(msg).to.equal('test');
        }
      },
```

The test was passing, I added console.log, but it wasn't executed, then I added `throw new Error('fail!');` but it still passed.

Then I changed the test to:

``` js
on: {
    'message': socketTester.shouldBeCalledNTimes(1)
},
```

and it failed with 

```
Error: AssertionError: expected 0 to equal 1
    at C:\virtual-boxes\hhvm\socketTester\index.js:68:17
    at Array.forEach (native)
    at null.<anonymous> (C:\virtual-boxes\hhvm\socketTester\index.js:62:27)
```

P.S. @alexzywiak  Please let me know if you are going to pay any attention to the issues I raised and if you are going to develop this project any further?

**Comment by Naktibalda** [comment]
I found the reason why my callback code was not executed.

It happened because testConditions timeout was fired before the end of setup, when only one 1 or 2 connections were created.

I think that it would be better to set the timeout after creating the last connection.

Another issue is that custom assertions set with

``` js
function(msg){
    expect(msg).to.equal('test');
}
```

do not fail if the message wasn't received.

**Comment by alexzywiak** [comment]
@Naktibalda - Thanks for bringing those to my attention.  I will take a look and try and make an update soon.
